'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Users",
      [
        {
          name: "Dipa",
          email: "dipa@gmail.com",
          password: "123",
          address: "Jl Pertanian Raya Kompl SLB A",
          phone: "085234236754",
          role: "tukang",
          service: "elektronik",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Amir",
          email: "amir@gmail.com",
          password: "123",
          address: "Jl Kayu Besar II 1 B, Dki Jakarta",
          phone: "081234647894",
          role: "tukang",
          service: "elektronik",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Taufik",
          email: "taufik@gmail.com",
          password: "123",
          address: "Jl Raya Pd Gede 30, Dki Jakarta",
          phone: "083312548030",
          role: "tukang",
          service: "elektronik",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Agus",
          email: "agus@gmail.com",
          password: "123",
          address: "JL. Letjend S Parman Kav. 21, Slipi",
          phone: "082289342039",
          role: "tukang",
          service: "elektronik",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Helmi",
          email: "helmi@gmail.com",
          password: "123",
          address: "Jl. Suka Jalan",
          phone: "0-21-765-7324",
          role: "tukang",
          service: "bangunan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Akbar",
          email: "akbar@gmail.com",
          password: "123",
          address: "Jl Sukarno Hatta 145",
          phone: "0-22-603-1577",
          role: "tukang",
          service: "bangunan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Setiawan Danial",
          email: "setiawan@gmail.com",
          password: "123",
          address: "Jl PLN 80, Dki Jakarta",
          phone: "0-21-735-2341",
          role: "tukang",
          service: "bangunan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Budi",
          email: "budi@gmail.com",
          password: "123",
          address: "Jl Harpa Raya",
          phone: "0-21-450-4831",
          role: "tukang",
          service: "bangunan",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Arul",
          email: "arul@gmail.com",
          password: "123",
          address: "Proy Senen Bl 1/76-77",
          phone: "0-21-421-0588",
          role: "tukang",
          service: "furniture",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Surya",
          email: "surya@gmail.com",
          password: "123",
          address: "Jl Kartini 23",
          phone: "0-61-567-7356",
          role: "tukang",
          service: "furniture",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Irfan",
          email: "irfan@gmail.com",
          password: "123",
          address: "Jl Kb Kacang Raya Ascott Tower",
          phone: "0-21-315-7453",
          role: "tukang",
          service: "furniture",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Putra",
          email: "putra@gmail.com",
          password: "123",
          address: "Jl Kalibaru Brt 16, Dki Jakarta",
          phone: "0-21-440-1388",
          role: "tukang",
          service: "furniture",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Izdihar",
          email: "izdihar@gmail.com",
          password: "123",
          address: "Jl Hang Lekir III/3, Dki Jakarta",
          phone: "0-21-726-6791",
          role: "tukang",
          service: "otomotif",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Wahyu",
          email: "wahyu@gmail.com",
          password: "123",
          address: "Jl Pluit Karang Cantik 40",
          phone: "0-21-661-0714",
          role: "tukang",
          service: "otomotif",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Dian",
          email: "dian@gmail.com",
          password: "123",
          address: "Jl Wijaya Tmr Raya 11",
          phone: "021-72788560",
          role: "tukang",
          service: "otomotif",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Harun",
          email: "harun@gmail.com",
          password: "123",
          address: "Jl Petogogan 1/37, Dki Jakarta",
          phone: "0-21-723-3860",
          role: "tukang",
          service: "otomotif",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Yanto",
          email: "yanto@gmail.com",
          password: "123",
          address: "Jl RS Fatmawati 6, Dki Jakarta",
          phone: "0-21-725-7338",
          role: "tukang",
          service: "cleaning",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Hasan",
          email: "hasan@gmail.com",
          password: "123",
          address: "Jl Mataram I 8, Dki Jakarta",
          phone: "0-21-720-7285",
          role: "tukang",
          service: "cleaning",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Adi",
          email: "adi@gmail.com",
          password: "123",
          address: "Jl Rahayu 1 A",
          phone: "0-21-565-9815",
          role: "tukang",
          service: "cleaning",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Faisal",
          email: "faisal@gmail.com",
          password: "123",
          address: "Jl KH Hasyim Ashari Dlm 11 L, Dki Jakarta",
          phone: "0-21-634-5651",
          role: "tukang",
          service: "cleaning",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },
};
